### ISSUE TITLE
Reference data for 2024/20

### ISSUE THREAD

**Issue by dloveall** [wimglenn/aocd-example-parser#13]
There are a lot of options for reference data on [this date](https://adventofcode.com/2024/day/20), but they aren't provided directly and are also not in a code or a pre. One option would be to directly provide some data, such as:
```
  "2024/20":  [
    {
      "answer_a":   "'44'",
      "answer_b":   "None",
      "extra":      {"minimum": 2}
    },
    {
      "answer_a":   "None",
      "answer_b":   "'285'",
      "extra":      {"minimum": 50}
    }
  ],
```
Most of the examples doing this are a few years old, and I wanted to see if this was still the preferred option. There are ultimately a lot more examples that could be created using the provided data. Converting the lists of equalities into minimums yields the following "minimum, result" pairs:
```
part_a = {2: 44, 4: 30, 6: 16, 8: 14, 10: 10, 12: 8, 20: 5, 36: 4, 38: 3, 40: 2, 64: 1}
part_b = {50: 285, 52: 253, 54: 222, 56: 193, 58: 154, 60: 129, 62: 106, 64: 86, 66: 67, 68: 55, 70: 41, 72: 29, 74: 7, 76: 3}
```

What is the current preferred method to write a reference data section for this type of input data?

**Comment by wimglenn** [comment]
Hmm, yes. These are both reasonable options.

I'm reminded of a 2015 puzzle that was similarly problematic for machine-parsing, the answer (4) was just written in the prose as "four". In that case I broke it down to smaller test cases, and "parsed" the answer by counting "#" glyphs. That was [`--- Day 18: Like a GIF For Your Yard ---`](https://adventofcode.com/2015/day/18).

In hindsight, it probably hasn't added much value having 9 different test cases there instead of just two, and if I did it again I'd probably provide the literal answer directly.

**Comment by wimglenn** [comment]
Note that we do put a locator for "li" elements, because there are many other examples that use those:

```
>>> from aocd.models import Puzzle
>>> from aocd.examples import Page
>>> page = Page.from_raw(Puzzle(2024, 20)._get_prose())
>>> page.a_li
[<li>There are 14 cheats that save 2 picoseconds.</li>,
 <li>There are 14 cheats that save 4 picoseconds.</li>,
 <li>There are 2 cheats that save 6 picoseconds.</li>,
 <li>There are 4 cheats that save 8 picoseconds.</li>,
 <li>There are 2 cheats that save 10 picoseconds.</li>,
 <li>There are 3 cheats that save 12 picoseconds.</li>,
 <li>There is one cheat that saves 20 picoseconds.</li>,
 <li>There is one cheat that saves 36 picoseconds.</li>,
 <li>There is one cheat that saves 38 picoseconds.</li>,
 <li>There is one cheat that saves 40 picoseconds.</li>,
 <li>There is one cheat that saves 64 picoseconds.</li>]
```
